<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>LoadGenerator.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Switchboard.Core\Switchboard.Core.csproj" />
	</ItemGroup>

</Project>
